name: terraform plan

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '**.tf'
      - '.tfnotify.yaml'

env:
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  tf-commit:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Tfnotify
        run: |
          sudo curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfnotify.tar.gz

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          reporter: github-pr-review
          fail_on_error: "false"
          filter_mode: "nofilter"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: true

      - name: Terraform Plan And Notify By Slack
        id: plan
        run: |
          terraform plan -no-color >> result.temp
          cat result.temp | tfnotify --config .tfnotify/github.yml plan --message "$(date)"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_BOT_NAME: tf-notify-bot
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        continue-on-error: true